apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    spec:
      containers:
      - name: my-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: AUTHOR
          value: "{{ .Values.author }}"
