apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: zelimhan/my-python-app:latest
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /hostname
            port: 8000
        livenessProbe:
          httpGet:
            path: /hostname
            port: 8000
